import {  JetBrains_Mono } from "next/font/google";
 
import "./globals.css";
import Header from "@/components/Header";
import PageTarnsition from "@/components/PageTarnsition";
import StairTarnsition from "@/components/StairTarnsition";

const JetBrainsMono = JetBrains_Mono({ subsets: ["latin"] ,weight:["100","200","300","400","500","600","700","800"], variable:"--font-jetbrainsMone" });

export const metadata = {
  title: "Belal Uddin Portfolio",
  description: "Generated by Belal Uddin",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={JetBrainsMono.className}>
      <Header/>
      <StairTarnsition/>
    <PageTarnsition>

    {children}
    </PageTarnsition>

 
        </body>
    </html>
  );
}
